#include <iostream>
#include <random>
#include <iomanip>
using namespace std;
class Game
{
    static mt19937 gen;

public:
    static int Number(int lower, int upper)
    {
        uniform_int_distribution<int> random(lower, upper);
        return random(gen);
    }
};

mt19937 Game::gen(random_device{}());
int main()
{
    Game player;
    int low_limit, upper_limit, chances = 5, number, flag = 0;
    cout << " Guess The Number Game \n";
    cout << setw(24) << setfill('*') << "" << endl;
    cout << " Enter the starting point of the range of random number :" << endl;
    cin >> low_limit;
    cout << " Enter the ending point of the range of random number :" << endl;
    cin >> upper_limit;
    if (low_limit==upper_limit)
    {
        cout << " Both the lower and upper limits are same , plz choose wisely ....\n";
        exit(1);
    }
    
    int random_number = player.Number(low_limit, upper_limit);
    for (int i = 0; i < chances; i++)
    {
        cout << "\n guess the number generated by computer \n ";
        cout << " This is your " << i + 1 << " chance out of 5 \n";
        cout << setw(50) << setfill('*') << "" << endl;
        cin >> number;
        if (number == random_number)
        {
            cout << " congrats !! you guess the write number in " << i + 1 << " chances ";
            cout << "\n If you enjoyed then visit again !!";
            flag++;
            exit(1);
        }
        else if (number < random_number)
        {
            cout << " The number you choose is less than the number choose by computer , enter a graeater number  \n";
        }
        else if (number > random_number)
        {
            cout << " The number you choose is greater than the number choose by computer , enter a lesser number  \n";
        }
        else
        {
            if ((number < low_limit) || (number > upper_limit))
            {
                cout << " \n plz Enter the number between the range \n";
            }
        }
    }
    if (flag == 0)
    {
        cout << " sorry buddy !! but you fail to choose the number seleted by computer ... \n";
        cout << " The random number is :" << random_number;
    }
    return 0;
}